//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAppointment1()
        {
            this.tblBookedAppointments = new HashSet<tblBookedAppointment>();
        }
    
        public int appointmentID { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<int> haircutID { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime expectedEndTime { get; set; }
        public decimal expectedPrice { get; set; }
        public string appointmentCancled { get; set; }
        public string cancledReason { get; set; }
    
        public virtual tblClient tblClient { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblHaircut tblHaircut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookedAppointment> tblBookedAppointments { get; set; }
    }
}
