//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment
    {
        public int AppointmentID { get; set; }
        public int EmployeeID { get; set; }
        public int CustomerID { get; set; }
        public int HaircutID { get; set; }
        public System.DateTime DateOfAppointment { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string IsBooked { get; set; }
    
        public virtual tblCustomerHistory tblCustomerHistory { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblHaircut tblHaircut { get; set; }
    }
}
