//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblAppointment
    {
        public int AppointmentID { get; set; }
        [Required]
        [Display(Name ="Hairdresser Name")]
        public int EmployeeID { get; set; }
        [Required]
        [Display(Name = "Customer Name")]
        public int CustomerID { get; set; }
        [Required]
        [Display(Name ="Haircut")]
        public int HaircutID { get; set; }
        [Required]
        [Display(Name = "Date Of Appointment")]
        public System.DateTime DateOfAppointment { get; set; }
        [Required]
        [Display(Name = "Start Time")]
        public System.TimeSpan StartTime { get; set; }
        [Required]
        [Display(Name = "End Time")]
        public System.TimeSpan EndTime { get; set; }
        [Required]
        public string IsBooked { get; set; }
    
        public virtual tblCustomerHistory tblCustomerHistory { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblHaircut tblHaircut { get; set; }
    }
}
