//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblAppointment
    {
        public int appointmentID { get; set; }
        [Required]
        [Display(Name ="Appointment Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        public DateTime appointmentDate { get; set; }
        public int employeeID { get; set; }
        public int clientID { get; set; }
        public int haircutID { get; set; }
        public int timeSlotID { get; set; }
    
        public virtual tblClient tblClient { get; set; }
        public virtual tblTimeSlot tblTimeSlot { get; set; }
    }
}
