//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClient()
        {
            this.tblAppointments = new HashSet<tblAppointment>();
        }
    
        public int clientID { get; set; }
        [Required]
        [Display(Name ="Name")]
        public string clientName { get; set; }
        [Required]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string clientMobile { get; set; }
        [Required]
        [Display(Name ="Email Address")]
        [DataType(DataType.EmailAddress)]
        public string clientEmail { get; set; }
        [Display(Name ="House Number")]
        public Nullable<int> clientHouseNumber { get; set; }
        public string clientHouseName { get; set; }
        [Required]
        [Display(Name ="Postal Code")]
        [DataType(DataType.PostalCode)]
        public string clientPostalCode { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string salt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppointment> tblAppointments { get; set; }
    }
}
