//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblCustomerHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomerHistory()
        {
            this.tblAppointments = new HashSet<tblAppointment>();
        }
        public int CustomerID { get; set; }
        [Required]
        [Display(Name ="Name")]
        public string CustomerName { get; set; }
        [Required]
        [Display(Name ="Phone Number")]
        public string CustomerPhoneNumber { get; set; }
        [Required]
        [Display(Name ="Phone Number")]
        public string CustomerEmailAddress { get; set; }
        [Required]
        [Display(Name ="House Number")]
        public string CustomerHouseNumber { get; set; }
        [Required]
        [Display(Name ="Postal Code")]
        public string CustomerPostalCode { get; set; }
        public Nullable<int> AppointmentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppointment> tblAppointments { get; set; }
    }
}
