//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmail
    {
        public int EmailID { get; set; }
        public string CustName { get; set; }
        public string custEmail { get; set; }
        public string custPhone { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string Read { get; set; }
        public System.DateTime DateSent { get; set; }
    }
}
