//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHaircut
    {
        public int HaircutID { get; set; }
        public string HaircutName { get; set; }
        public Nullable<double> ShortPrice { get; set; }
        public Nullable<double> LongPrice { get; set; }
        public Nullable<System.TimeSpan> TimeToCompletion { get; set; }
        public Nullable<int> TypeID { get; set; }
        public bool isSelected { get; set; }
    
        public virtual tblHaircutType tblHaircutType { get; set; }
        public virtual tblAppointment tblAppointment { get; set; }
    }
}
