//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblHaircut
    {
        public int HaircutID { get; set; }
        [Required(ErrorMessage = "A haircut name is required!")]
        [Display(Name ="Haircut Name")]
        public string HaircutName { get; set; }
        [Required(ErrorMessage = "Please enter the cost for short hair")]
        [DataType(DataType.Currency)]
        [Display(Name ="Short Price")]
        public Nullable<double> ShortPrice { get; set; }
        [Required(ErrorMessage = "Please enter the cost for long hair")]
        [DataType(DataType.Currency)]
        [Display(Name = "Long Price")]
        public Nullable<double> LongPrice { get; set; }
        [Required]
        [DataType(DataType.Time)]
        [Display(Name ="Duration")]
        public Nullable<System.TimeSpan> TimeToCompletion { get; set; }
        [Required]
        [Display(Name = "Category")]
        public int TypeID { get; set; }
        public bool isSelected { get; set; }
    
        public virtual tblHaircutType tblHaircutType { get; set; }
    }
}
