//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblHaircut
    {
        public int HaircutID { get; set; }
        [Required]
        [Display(Name ="Haircut Name")]
        public string HaircutName { get; set; }
        [Required]
        [Display(Name ="Short Price")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> ShortPrice { get; set; }
        [Required]
        [Display(Name ="Long Price")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> LongPrice { get; set; }
        [Display(Name = "Type Name")]
        public Nullable<int> TypeID { get; set; }
        public bool isSelected { get; set; }
    
        public virtual tblHaircutType tblHaircutType { get; set; }
    }
}
