//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mobileHairdresser.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblWorkingDay
    {
        public int DayID { get; set; }
        [Required]
        [Display(Name = "Day of The Week")]
        public string DayName { get; set; }
        [Required]
        [Display(Name = "Start Time")]
        public Nullable<System.TimeSpan> StartTime { get; set; }
        [Required]
        [Display(Name ="End Time")]
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
